# .sops.yaml

keys:
  - &wsl-laptop-e431 age1f5jar4fe3fy8pqs9qkvs7y72etnsaekxv9fr08nem5svt3l9meusaw4zqt
creation_rules:
  - path_regex: secrets/hosts
    key_groups:
    - age:
      - *wsl-laptop-e431
  - path_regex: .yaml$
    key_groups:
    - age:
      - *wsl-laptop-e431
