# .sops.yaml

keys:
  - &voxxus ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOvfKXZIlS+G2z2Aws7MjGUHdVqoGNCFkWeKvX2w41Wl

creation_rules:
  - path_regex: secrets/voxxus\.yaml
    key_groups:
    - age:
      - *voxxus
