# .sops.yaml

keys:
  - &voxxus ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOdQL526T83qJ+JVXfBiNrcyCPqnxSkFYwi+dp+YCpF9

creation_rules:
  - path_regex: secrets/voxxus\.yaml
    key_groups:
    - age:
      - *voxxus
